# NGINX
# ====================================================

- name: Add Nginx latest version ppa
  action: apt_repository repo=ppa:nginx/stable

- name: Update APT
  command: sudo apt-get update

- name: Install Nginx
  action: apt name=nginx

- name: Delete default vhost
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Copy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }}

- name: Create sites-enabled symlink
  file: src=/etc/nginx/sites-available/{{ app_name }} dest=/etc/nginx/sites-enabled/{{ app_name }} state=link
  notify:
  - restart nginx
